site_name: My Docs
nav:
  - "index.md"
  - "mkdocs-with-pdf.md"
  - "mkdocs-with-pdf-output.md"
use_directory_urls: false

theme:
  name: material
  language: ja

plugins:
  - with-pdf:
      author: Author
      copyright: CopyRight
      # cover: true
      # cover_title: TITLE TEXT
      # cover_subtitle: SUBTITLE TEXT
      custom_template_path: custom_template
      debug_html: false
      toc_title: 目次
      two_columns_level: 3
      exclude_pages:
        - mkdocs-with-pdf-output.html

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences

extra_javascript:
  - js/custom.js
extra_css:
  - css/custom.css
