site_name: My Docs
nav:
  - "index.md"
  - "mkdocs-with-pdf.md"
  - "mkdocs-with-pdf-output.md"
use_directory_urls: false

theme:
  name: material
  language: ja

plugins:
  - with-pdf:
      author: Author
      copyright: CopyRight
      # cover: true
      # cover_title: TITLE TEXT
      # cover_subtitle: SUBTITLE TEXT
      back_cover: true
      custom_template_path: custom_template
      debug_html: true
      show_anchors: false
      toc_title: 目次
      toc_level: 3
      two_columns_level: 3
      exclude_pages:
        - index.html
        - mkdocs-with-pdf-output.html
  - toc-md:
      toc_page_title: 目次
      toc_page_description: PDF Generate Plugin for MkDocsを使用して、ドキュメントをPDFとして出力します。
      header_level: 3
      pickup_description_meta: false
      pickup_description_class: false
      output_path: index.md
      output_log: true
      ignore_page_pattern: index.md
      remove_navigation_page_pattern: index.md

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences

extra_javascript:
  - js/custom.js
extra_css:
  - css/custom.css
